### ISSUE TITLE
Use pipe as separator

### ISSUE THREAD

**Issue by TheDon2866** [Saunved/get-grid#3]
Quick question... Why don't you use pipes to show we have a new column? Would be more intuitive to me.

**Comment by Saunved** [comment]
Hi, 
We're using / to separate rows. I think using | to separate columns could reduce readability.

That said, I'm thinking of adding a config file where each person can specify their own preferences for certain presets and use get-grid however they want.

So in a future update, you could set a "defaultColumnSeparator" value to "|" and use get-grid that way. 

Not sure when this will be implemented, but I will add it to my to-do list. Thanks for the suggestion :)
