### ISSUE TITLE
'get-grid' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by HarryAdney** [Saunved/get-grid#4]
Windows 10 Pro (Insider)
Norton 360 - in case that's the problem
VSCode opened as administrator, using internal terminal.

It appears to install globally, but the error is returned on all get-grid commands.

**Comment by Saunved** [comment]
Hi, thanks for the report.
A few quick questions:
1) Are you trying to run the command inside of the VSCode terminal? If yes, could you try running it in "cmd" with admin permissions and check?
2) If that doesn't work, try installing the latest version using 
```shell
npm i get-grid@next -g
```

If both these approaches don't work, please let me know. I had tested this on Windows 10 Home (cmd) and it seemed to work.

**Comment by HarryAdney** [comment]
Hi thanks for getting back to me.
I've tried both methods without success. Please see attached image.

I've actually closed cmd and reopened as administrator, though the image doesn't show this. Same result though.

I've checked that get-grid is in my system variables path, but it isn't in my user path. Could that be the problem?

Thanks.

**Comment by HarryAdney** [comment]
Hi Saunvad,

The problem was with my environment varialbes. I added the correct folder and it worked no problem.

Many thanks.

**Comment by Saunved** [comment]
Hi Harry,
Glad to know the issue was fixed. 
Cheers :+1:
